data:
  files:
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018D-v1+RAW_Aug15_18_data_invertoffline.root
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018A-v1+RAW_Aug15_18_data_invertoffline.root
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018B-v1+RAW_Aug15_18_data_invertoffline.root
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018C-v1+RAW_Aug15_18_data_invertoffline.root
  type:
    data
  color: 895

expected:
  files:
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018D-v1+RAW_Aug15_18_data_invertoffline.root
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018A-v1+RAW_Aug15_18_data_invertoffline.root
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018B-v1+RAW_Aug15_18_data_invertoffline.root
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2018C-v1+RAW_Aug15_18_data_invertoffline.root
  type:
    data
  color: 895

GluGluToSUEP_HT400_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS400.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS1000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS700.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS800.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS2000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS2000.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS1500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS1500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS125.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS900.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS300.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS1200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS1200.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS600.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Aug15_18_generic_invertoffline.root
  type:
    signal

