data:
  files:
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2017C-v1+RAW_Jan14_2017_unblindtest.root
  type:
    data
  color: 895

expected:
  files:
    - /data/submit/jinw65/SUEP/outputs//ScoutingPFHT+Run2017C-v1+RAW_Jan14_2017_unblindtest.root
  type:
    data
  color: 895

GluGluToSUEP_HT400_T1p00_mS1500.000_mPhi2.000_T1.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T1p00_mS1500.000_mPhi2.000_T1.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T6p00_mS1500.000_mPhi3.000_T6.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T6p00_mS1500.000_mPhi3.000_T6.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T2p00_mS1500.000_mPhi2.000_T2.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T2p00_mS1500.000_mPhi2.000_T2.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T4p00_mS1500.000_mPhi8.000_T4.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T4p00_mS1500.000_mPhi8.000_T4.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T8p00_mS1500.000_mPhi8.000_T8.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T8p00_mS1500.000_mPhi8.000_T8.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T1p50_mS1500.000_mPhi3.000_T1.500_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T1p50_mS1500.000_mPhi3.000_T1.500_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T16p0_mS1500.000_mPhi4.000_T16.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T16p0_mS1500.000_mPhi4.000_T16.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T2p00_mS1500.000_mPhi8.000_T2.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T2p00_mS1500.000_mPhi8.000_T2.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T8p00_mS1500.000_mPhi2.000_T8.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T8p00_mS1500.000_mPhi2.000_T8.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T8p00_mS1500.000_mPhi4.000_T8.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T8p00_mS1500.000_mPhi4.000_T8.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T3p00_mS1500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T3p00_mS1500.000_mPhi3.000_T3.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T0p50_mS1500.000_mPhi2.000_T0.500_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T0p50_mS1500.000_mPhi2.000_T0.500_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T1p00_mS1500.000_mPhi4.000_T1.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T1p00_mS1500.000_mPhi4.000_T1.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T16p0_mS1500.000_mPhi8.000_T16.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T16p0_mS1500.000_mPhi8.000_T16.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T0p75_mS1500.000_mPhi3.000_T0.750_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T0p75_mS1500.000_mPhi3.000_T0.750_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T12p0_mS1500.000_mPhi3.000_T12.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T12p0_mS1500.000_mPhi3.000_T12.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T4p00_mS1500.000_mPhi2.000_T4.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T4p00_mS1500.000_mPhi2.000_T4.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T32p0_mS1500.000_mPhi8.000_T32.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T32p0_mS1500.000_mPhi8.000_T32.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T4p00_mS1500.000_mPhi4.000_T4.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T4p00_mS1500.000_mPhi4.000_T4.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

GluGluToSUEP_HT400_T2p00_mS1500.000_mPhi4.000_T2.000_modegeneric_TuneCP5_13TeV-pythia8:
  files:
    - /data/submit/jinw65/SUEP/outputs//GluGluToSUEP_HT400_T2p00_mS1500.000_mPhi4.000_T2.000_modegeneric_TuneCP5_13TeV_Jan14_2017_unblindtest.root
  type:
    signal

